version: '3.7'

services:
  comdevguto:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/src/app
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: effective-chainsaw
    expose:
      - '3333'
    ports:
      - '3333:3333'
    command: npm run dev
